#!/bin/sh

nohup /app/jdk1.8.0_72/bin/java -server -Ddaemon.name=nimbus -Dstorm.options= -Dstorm.home=/app/apache-storm-1.0.2 -Dstorm.log.dir=/app/apache-storm-1.0.2/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file=/data/storm-1.0.2/cluster_1/conf/nimbus/storm.yaml -cp /app/apache-storm-1.0.2/lib/servlet-api-2.5.jar:/app/apache-storm-1.0.2/lib/objenesis-2.1.jar:/app/apache-storm-1.0.2/lib/reflectasm-1.10.1.jar:/app/apache-storm-1.0.2/lib/log4j-over-slf4j-1.6.6.jar:/app/apache-storm-1.0.2/lib/disruptor-3.3.2.jar:/app/apache-storm-1.0.2/lib/storm-core-1.0.2.jar:/app/apache-storm-1.0.2/lib/log4j-slf4j-impl-2.1.jar:/app/apache-storm-1.0.2/lib/clojure-1.7.0.jar:/app/apache-storm-1.0.2/lib/slf4j-api-1.7.7.jar:/app/apache-storm-1.0.2/lib/asm-5.0.3.jar:/app/apache-storm-1.0.2/lib/log4j-core-2.1.jar:/app/apache-storm-1.0.2/lib/minlog-1.3.0.jar:/app/apache-storm-1.0.2/lib/kryo-3.0.3.jar:/app/apache-storm-1.0.2/lib/log4j-api-2.1.jar:/app/apache-storm-1.0.2/lib/storm-rename-hack-1.0.2.jar:/data/storm-1.0.2/cluster_1/conf/nimbus -Xmx1024m -Dlogfile.name=nimbus.log -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j.configurationFile=/data/storm-1.0.2/cluster_1/conf/nimbus/cluster.xml org.apache.storm.daemon.nimbus > /dev/null 2>&1 &


nohup /app/jdk1.8.0_72/bin/java -server -Ddaemon.name=supervisor -Dstorm.options= -Dstorm.home=/app/apache-storm-1.0.2 -Dstorm.log.dir=/app/apache-storm-1.0.2/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file=/data/storm-1.0.2/cluster_1/conf/supervisor_1/storm.yaml -cp /app/apache-storm-1.0.2/lib/servlet-api-2.5.jar:/app/apache-storm-1.0.2/lib/objenesis-2.1.jar:/app/apache-storm-1.0.2/lib/reflectasm-1.10.1.jar:/app/apache-storm-1.0.2/lib/log4j-over-slf4j-1.6.6.jar:/app/apache-storm-1.0.2/lib/disruptor-3.3.2.jar:/app/apache-storm-1.0.2/lib/storm-core-1.0.2.jar:/app/apache-storm-1.0.2/lib/log4j-slf4j-impl-2.1.jar:/app/apache-storm-1.0.2/lib/clojure-1.7.0.jar:/app/apache-storm-1.0.2/lib/slf4j-api-1.7.7.jar:/app/apache-storm-1.0.2/lib/asm-5.0.3.jar:/app/apache-storm-1.0.2/lib/log4j-core-2.1.jar:/app/apache-storm-1.0.2/lib/minlog-1.3.0.jar:/app/apache-storm-1.0.2/lib/kryo-3.0.3.jar:/app/apache-storm-1.0.2/lib/log4j-api-2.1.jar:/app/apache-storm-1.0.2/lib/storm-rename-hack-1.0.2.jar:/data/storm-1.0.2/cluster_1/conf/supervisor_1 -Xmx256m -Dlogfile.name=supervisor.log -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j.configurationFile=/data/storm-1.0.2/cluster_1/conf/supervisor_1/cluster.xml org.apache.storm.daemon.supervisor > /dev/null 2>&1 &


nohup /app/jdk1.8.0_72/bin/java -server -Ddaemon.name=supervisor -Dstorm.options= -Dstorm.home=/app/apache-storm-1.0.2 -Dstorm.log.dir=/app/apache-storm-1.0.2/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file=/data/storm-1.0.2/cluster_1/conf/supervisor_2/storm.yaml -cp /app/apache-storm-1.0.2/lib/servlet-api-2.5.jar:/app/apache-storm-1.0.2/lib/objenesis-2.1.jar:/app/apache-storm-1.0.2/lib/reflectasm-1.10.1.jar:/app/apache-storm-1.0.2/lib/log4j-over-slf4j-1.6.6.jar:/app/apache-storm-1.0.2/lib/disruptor-3.3.2.jar:/app/apache-storm-1.0.2/lib/storm-core-1.0.2.jar:/app/apache-storm-1.0.2/lib/log4j-slf4j-impl-2.1.jar:/app/apache-storm-1.0.2/lib/clojure-1.7.0.jar:/app/apache-storm-1.0.2/lib/slf4j-api-1.7.7.jar:/app/apache-storm-1.0.2/lib/asm-5.0.3.jar:/app/apache-storm-1.0.2/lib/log4j-core-2.1.jar:/app/apache-storm-1.0.2/lib/minlog-1.3.0.jar:/app/apache-storm-1.0.2/lib/kryo-3.0.3.jar:/app/apache-storm-1.0.2/lib/log4j-api-2.1.jar:/app/apache-storm-1.0.2/lib/storm-rename-hack-1.0.2.jar:/data/storm-1.0.2/cluster_1/conf/supervisor_2 -Xmx256m -Dlogfile.name=supervisor.log -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j.configurationFile=/data/storm-1.0.2/cluster_1/conf/supervisor_2/cluster.xml org.apache.storm.daemon.supervisor > /dev/null 2>&1 &


nohup /app/jdk1.8.0_72/bin/java -server -Ddaemon.name=supervisor -Dstorm.options= -Dstorm.home=/app/apache-storm-1.0.2 -Dstorm.log.dir=/app/apache-storm-1.0.2/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file=/data/storm-1.0.2/cluster_1/conf/supervisor_3/storm.yaml -cp /app/apache-storm-1.0.2/lib/servlet-api-2.5.jar:/app/apache-storm-1.0.2/lib/objenesis-2.1.jar:/app/apache-storm-1.0.2/lib/reflectasm-1.10.1.jar:/app/apache-storm-1.0.2/lib/log4j-over-slf4j-1.6.6.jar:/app/apache-storm-1.0.2/lib/disruptor-3.3.2.jar:/app/apache-storm-1.0.2/lib/storm-core-1.0.2.jar:/app/apache-storm-1.0.2/lib/log4j-slf4j-impl-2.1.jar:/app/apache-storm-1.0.2/lib/clojure-1.7.0.jar:/app/apache-storm-1.0.2/lib/slf4j-api-1.7.7.jar:/app/apache-storm-1.0.2/lib/asm-5.0.3.jar:/app/apache-storm-1.0.2/lib/log4j-core-2.1.jar:/app/apache-storm-1.0.2/lib/minlog-1.3.0.jar:/app/apache-storm-1.0.2/lib/kryo-3.0.3.jar:/app/apache-storm-1.0.2/lib/log4j-api-2.1.jar:/app/apache-storm-1.0.2/lib/storm-rename-hack-1.0.2.jar:/data/storm-1.0.2/cluster_1/conf/supervisor_3 -Xmx256m -Dlogfile.name=supervisor.log -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j.configurationFile=/data/storm-1.0.2/cluster_1/conf/supervisor_3/cluster.xml org.apache.storm.daemon.supervisor > /dev/null 2>&1 &


nohup /app/jdk1.8.0_72/bin/java -server -Ddaemon.name=ui -Dstorm.options= -Dstorm.home=/app/apache-storm-1.0.2 -Dstorm.log.dir=/app/apache-storm-1.0.2/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file=/data/storm-1.0.2/cluster_1/conf/ui/storm.yaml -cp /app/apache-storm-1.0.2/lib/servlet-api-2.5.jar:/app/apache-storm-1.0.2/lib/objenesis-2.1.jar:/app/apache-storm-1.0.2/lib/reflectasm-1.10.1.jar:/app/apache-storm-1.0.2/lib/log4j-over-slf4j-1.6.6.jar:/app/apache-storm-1.0.2/lib/disruptor-3.3.2.jar:/app/apache-storm-1.0.2/lib/storm-core-1.0.2.jar:/app/apache-storm-1.0.2/lib/log4j-slf4j-impl-2.1.jar:/app/apache-storm-1.0.2/lib/clojure-1.7.0.jar:/app/apache-storm-1.0.2/lib/slf4j-api-1.7.7.jar:/app/apache-storm-1.0.2/lib/asm-5.0.3.jar:/app/apache-storm-1.0.2/lib/log4j-core-2.1.jar:/app/apache-storm-1.0.2/lib/minlog-1.3.0.jar:/app/apache-storm-1.0.2/lib/kryo-3.0.3.jar:/app/apache-storm-1.0.2/lib/log4j-api-2.1.jar:/app/apache-storm-1.0.2/lib/storm-rename-hack-1.0.2.jar:/app/apache-storm-1.0.2:/data/storm-1.0.2/cluster_1/conf/ui -Xmx768m -Dlogfile.name=ui.log -DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j.configurationFile=/data/storm-1.0.2/cluster_1/conf/ui/cluster.xml org.apache.storm.ui.core > /dev/null 2>&1 &


